version: '3.7'

services:
  sonarqube:
    container_name: sonar
    restart: always
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - net1
  jenkins:
    container_name: nice_gates
    restart: always
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    depends_on:
      - sonarqube
    networks:
      - net1

networks:
  net1:
    driver: bridge