version: '3.7'

services:
  sonarqube:
    container_name: sonar
    restart: always
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - cicd-network
  jenkins:
    container_name: nice_gates
    restart: always
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    networks:
      - cicd-network
    environment:
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"

networks:
  cicd-network  :
    driver: bridge